//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplications.Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientApplications.Resources.Messages.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone is now confirmed!.
        /// </summary>
        public static string CellPhoneNumberAlreadyVerified {
            get {
                return ResourceManager.GetString("CellPhoneNumberAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is duplicated! Please use another value..
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is set as a reminder!.
        /// </summary>
        public static string EmailIsSetAsReminder {
            get {
                return ResourceManager.GetString("EmailIsSetAsReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email must contain consent!.
        /// </summary>
        public static string EmailMustContainConsent {
            get {
                return ResourceManager.GetString("EmailMustContainConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the {0} field must be exactly {1} digits!.
        /// </summary>
        public static string FixLengthNumeric {
            get {
                return ResourceManager.GetString("FixLengthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid!.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value is invalid..
        /// </summary>
        public static string InvalidRegularExpression {
            get {
                return ResourceManager.GetString("InvalidRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The verification code is not correct!.
        /// </summary>
        public static string InvalidVerificationKey {
            get {
                return ResourceManager.GetString("InvalidVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the {0} field can be up to {1} characters!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the {0} field must be at least {1} characters!.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minor client must have at least one guardian.
        /// </summary>
        public static string MinorClientMustHaveAtLeastOneGuardian {
            get {
                return ResourceManager.GetString("MinorClientMustHaveAtLeastOneGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is set as text reminder!.
        /// </summary>
        public static string PhoneNumberIsSetAsTextReminder {
            get {
                return ResourceManager.GetString("PhoneNumberIsSetAsTextReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is set as voice reminder!.
        /// </summary>
        public static string PhoneNumberIsSetAsVoiceReminder {
            get {
                return ResourceManager.GetString("PhoneNumberIsSetAsVoiceReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must selected as text message ok!.
        /// </summary>
        public static string PhoneNumberMustSelectedAsTextMessageOk {
            get {
                return ResourceManager.GetString("PhoneNumberMustSelectedAsTextMessageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must selected as voice message ok!.
        /// </summary>
        public static string PhoneNumberMustSelectedAsVoiceMessageOk {
            get {
                return ResourceManager.GetString("PhoneNumberMustSelectedAsVoiceMessageOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of the {0} field must be greater than or equal to {1} and less than or equal to {2}..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
    }
}
